Table observability {
  asset_id           serial [pk]
  obs_ip_address     text [not null]
  obs_hostname       text [not null]
  obs_fqdn           text [not null] // Pristine 
  obs_status         text [not null] 
}

Table inventory {
  inv_ip_address     text [pk]
  inv_hostname       text [not null]
  inv_vendor         text [not null]
  inv_model          text [not null]
}

Table ipam {
  ipam_ip_address    text [pk]
  ipam_fqdn          text [not null]
  ipam_region        text [not null]
}

Table labels {
  asset_id           int [pk, ref: > observability.asset_id]
  is_in_inventory    boolean
  is_in_ipam         boolean
}